//AUTOGENERATED FILE FROM png2asset
// Conversion args: background.png -o background.c -map -keep_palette_order -tile_origin 3

#ifndef METASPRITE_background_H
#define METASPRITE_background_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define background_TILE_ORIGIN 3
#define background_TILE_W 8
#define background_TILE_H 8
#define background_WIDTH 160
#define background_HEIGHT 144
#define background_TILE_COUNT 7
#define background_PALETTE_COUNT 1
#define background_COLORS_PER_PALETTE 4
#define background_TOTAL_COLORS 4
#define background_MAP_ATTRIBUTES 0
extern const unsigned char background_map[360];
#define background_map_attributes background_map

BANKREF_EXTERN(background)

extern const palette_color_t background_palettes[4];
extern const uint8_t background_tiles[112];

#endif
