//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_character8x16_H
#define METASPRITE_character8x16_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define character8x16_TILE_ORIGIN 0
#define character8x16_TILE_W 8
#define character8x16_TILE_H 16
#define character8x16_WIDTH 16
#define character8x16_HEIGHT 16
#define character8x16_TILE_COUNT 4
#define character8x16_PALETTE_COUNT 1
#define character8x16_COLORS_PER_PALETTE 4
#define character8x16_TOTAL_COLORS 4
#define character8x16_PIVOT_X 8
#define character8x16_PIVOT_Y 8
#define character8x16_PIVOT_W 16
#define character8x16_PIVOT_H 16

BANKREF_EXTERN(character8x16)

extern const palette_color_t character8x16_palettes[4];
extern const uint8_t character8x16_tiles[64];

extern const metasprite_t* const character8x16_metasprites[1];

#endif
