//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(circlesprite8x8)

const palette_color_t circlesprite8x8_palettes[4] = {
	RGB8(255,255,255), RGB8(182,182,182), RGB8(138,138,138), RGB8(  0,  0,  0)
	
};

const uint8_t circlesprite8x8_tiles[32] = {
	0x3c,0x3c,0x7e,0x76,
	0xff,0xe7,0xff,0xf7,
	0xff,0xf7,0xff,0xf7,
	0x7e,0x62,0x3c,0x3c,
	
0x3c,0x3c,0x7e,0x7e,
	0xff,0xc3,0xff,0xfb,
	0xff,0xc3,0xff,0xdf,
	0x7e,0x42,0x3c,0x3c
	
};

const metasprite_t circlesprite8x8_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, 0), METASPR_ITEM(8, 0, 1, 0), METASPR_TERM
};

const metasprite_t* const circlesprite8x8_metasprites[1] = {
	circlesprite8x8_metasprite0
};
