//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_circlesprite8x8_H
#define METASPRITE_circlesprite8x8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define circlesprite8x8_TILE_ORIGIN 0
#define circlesprite8x8_TILE_W 8
#define circlesprite8x8_TILE_H 8
#define circlesprite8x8_WIDTH 8
#define circlesprite8x8_HEIGHT 16
#define circlesprite8x8_TILE_COUNT 2
#define circlesprite8x8_PALETTE_COUNT 1
#define circlesprite8x8_COLORS_PER_PALETTE 4
#define circlesprite8x8_TOTAL_COLORS 4
#define circlesprite8x8_PIVOT_X 4
#define circlesprite8x8_PIVOT_Y 8
#define circlesprite8x8_PIVOT_W 8
#define circlesprite8x8_PIVOT_H 16

BANKREF_EXTERN(circlesprite8x8)

extern const palette_color_t circlesprite8x8_palettes[4];
extern const uint8_t circlesprite8x8_tiles[32];

extern const metasprite_t* const circlesprite8x8_metasprites[1];

#endif
