//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gbdk_rocks_colored_H
#define METASPRITE_gbdk_rocks_colored_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbdk_rocks_colored_TILE_ORIGIN 0
#define gbdk_rocks_colored_TILE_W 8
#define gbdk_rocks_colored_TILE_H 8
#define gbdk_rocks_colored_WIDTH 160
#define gbdk_rocks_colored_HEIGHT 144
#define gbdk_rocks_colored_TILE_COUNT 139
#define gbdk_rocks_colored_PALETTE_COUNT 4
#define gbdk_rocks_colored_COLORS_PER_PALETTE 4
#define gbdk_rocks_colored_TOTAL_COLORS 16
#define gbdk_rocks_colored_MAP_ATTRIBUTES gbdk_rocks_colored_map_attributes
#define gbdk_rocks_colored_MAP_ATTRIBUTES_WIDTH 20
#define gbdk_rocks_colored_MAP_ATTRIBUTES_HEIGHT 18
#define gbdk_rocks_colored_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define gbdk_rocks_colored_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(gbdk_rocks_colored)

extern const palette_color_t gbdk_rocks_colored_palettes[16];
extern const uint8_t gbdk_rocks_colored_tiles[2224];

extern const unsigned char gbdk_rocks_colored_map[360];
extern const unsigned char gbdk_rocks_colored_map_attributes[360];

#endif
