//AUTOGENERATED FILE FROM png2asset
// Conversion args: tetromino.png -o tetromino.c -keep_palette_order -spr8x8

#ifndef METASPRITE_tetromino_H
#define METASPRITE_tetromino_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tetromino_TILE_ORIGIN 0
#define tetromino_TILE_W 8
#define tetromino_TILE_H 8
#define tetromino_WIDTH 24
#define tetromino_HEIGHT 8
#define tetromino_TILE_COUNT 3
#define tetromino_PALETTE_COUNT 1
#define tetromino_COLORS_PER_PALETTE 4
#define tetromino_TOTAL_COLORS 4
#define tetromino_PIVOT_X 12
#define tetromino_PIVOT_Y 4
#define tetromino_PIVOT_W 24
#define tetromino_PIVOT_H 8
extern const metasprite_t* const tetromino_metasprites[1];

BANKREF_EXTERN(tetromino)

extern const palette_color_t tetromino_palettes[4];
extern const uint8_t tetromino_tiles[48];

#endif
